-- Polecenia DROP dla tabel
DROP TABLE IF EXISTS Oferta_ubezpieczenia_zależna_od_pakietu;
DROP TABLE IF EXISTS Oferta_ubezpieczenia_zależna_od_kierowcy;
DROP TABLE IF EXISTS Oferta_zniżek_pakietu;
DROP TABLE IF EXISTS Oferta_zniżek_kierowcy;
DROP TABLE IF EXISTS Znizki_lojalnosciowa;
DROP TABLE IF EXISTS Znizki_za_brak_wypadkow;
DROP TABLE IF EXISTS Znizki_za_prawo_jazdy;
DROP TABLE IF EXISTS Oferta_dla_polisy;
DROP TABLE IF EXISTS Oferta_ubezpieczenia;
DROP TABLE IF EXISTS Polisa;
DROP TABLE IF EXISTS Katalog_wyceny_pojazdu;
DROP TABLE IF EXISTS Użytkowanie_samochodu;
DROP TABLE IF EXISTS Posiadanie;
DROP TABLE IF EXISTS Stan_posiadania;
DROP TABLE IF EXISTS Samochód;
DROP TABLE IF EXISTS Posiadanie_wypadków;
DROP TABLE IF EXISTS Historia_wypadków;
DROP TABLE IF EXISTS Właściciel;
